### ISSUE TITLE
Add Shift-Space for Next/Down

### ISSUE THREAD

**Issue by kickingvegas** [kickingvegas/casual-info#12]
### Discussed in https://github.com/kickingvegas/casual-info/discussions/11

<div type='discussions-op-text'>

<sup>Originally posted by **Rolly-GitHub** June  5, 2024</sup>
The Transient menu has bound to Info-scroll-up:
\<space\>  Next/Down

Suggest you follow that item next with:
\<S-space\> Prev/Up

bound to Info-scroll-down.

Note: Maybe it would be "S-\<space\>" rather than "\<S-space\>" to represent Shift-Space.
... Not sure what the "best" or correct way to list that key sequence.</div>

**Comment by Rolly-GitHub** [comment]
Probably should have initially called this "Add Shift-Space for Prev/Up"
Sorry. My mistake!

**Comment by kickingvegas** [comment]
The semantics of scrolling up/down are ~from hell~ awkward.

This screenshot shows what unicode glyphs I'm using to help discern the scrolling intent.

<img width="705" alt="Screenshot 2024-06-06 at 1 25 54 PM" src="https://github.com/kickingvegas/casual-info/assets/395760/89a45f5d-3c62-4a1d-87c9-b1c04e20fc21">

**Comment by kickingvegas** [comment]
@Rolly-GitHub v1.1.0 released and available on MELPA. https://github.com/kickingvegas/casual-info/releases/tag/1.1.0
