### ISSUE TITLE
Conform Info Navigation to Transient Conventions

### ISSUE THREAD

**Issue by tarsius** [kickingvegas/casual-info#9]
IMO the key used to "dismiss" the current transient menu should be the same used elsewhere in Emacs to abort the current "incomplete" (or otherwise "stuck") action: `C-g`.

All transient already bind `C-g` to the appropriate command[^1], so there is no need to bind another key, and/or to use a non-trivial suffix definition (such as your `("q" "Dismiss" ignore :transient transient--do-exit)`).

My recommendation would be to just drop that altogether and relay on the existing `C-g` binding. But the argument could be made that to users new to transient, that is not obvious, so the suffix should be displayed. My counter argument is that `C-g` is used all across Emacs, without a visual hint that in any given context it is available too, just like in nearly all other contexts.

Also see A.7 at https://magit.vc/manual/transient/How-can-I-autoload-prefix-and-suffix-commands_003f.html#Why-does-q-not-quit-popups-anymore_003f-1. I.e. in this menu `q` should quit the info buffer (and maybe *also* (not *only*) the info transient menu).

[^1]: `transient-quit-one`; though in certain special contexts another command is bound, but you don't have to worry about that.

**Comment by kickingvegas** [comment]
@tarsius Thanks much for the input! I do appreciate your insights into this. I have a couple of questions and observations on the UX behavior and conventions for changing activity with Transients, particularly for nested menus. I see a couple of scenarios where:

1.  All menus are dismissed.
2.  The current menu is dismissed and its parent menu is displayed.
3.  A menu item will quit the actual mode (for example `calc-quit`).
4.  A long-running command (potentially asynchronous) is to be cancelled while the menu is still raised (and possibly be dynamically updated).

The UX convention I’ve implemented at current for the Casual menus does this:

| Label   | Binding | Command                    | Notes                   |
|------- |------- |-------------------------- |----------------------- |
| ‹Back   | `C-g`   | transient&#x2013;do-return | This covers scenario 2. |
| Dismiss | `q`     | transient&#x2013;do-exit   | This covers scenario 1. |

At current I do not cover cases 3 and 4.

While your suggestion to just rely on `C-g` can apply to workflows with only a single menu, I’m struggling to find a convention for handling scenario 1 with that same guidance, much less for scenario 4. I understand the motivation for reserving the binding `q` to apply to the mode which my convention currently violates.

I claim no monopoly on the “right” answer here, but wonder if there has been any effort to focus-test these ideas. I’m reluctant to accept that implicit knowledge of `C-g` is going to be satisfactory for addressing all the scenarios enumerated above.

**Comment by tarsius** [comment]
The command for (1) is `transient-quit-one`. (It isn't necessary to add an additional command that just uses the "pre-command` `transient--do-exit` and avoids the "unnecessary complexity" in the `transient--do-quit-one` pre-command. That complexity is there to handle different situation where you would also want to abort the "most local context". If you don't implement a different, incomplete "quit just this" command, then you get consistent behavior for free.

(As an example, if you set out to type `P - f p` in Magit to force push, but after `P -` you realize, that you don't want/have to force push, then `C-g` takes you back to the state after you originally typed `P`; it doesn't take you out of the menu altogether.)

The command for (2) is `transient-quit-all`. The binding is `C-q`.

For (3), `q` is usually the appropriate binding -- at least when `q` outside the menu, would perform the same action.

The best binding for (4) depends on the specific use-case. Or maybe I just cannot think of a "universally appropriate" binding for this right now.

**Comment by kickingvegas** [comment]
@tarsius Thanks for communicating this. Upon consideration I’ll take the following action items:

1.  Map `C-g` to `transient-quit-one` for the “‹Back” action to conform with existing Transient convention.
2.  Change binding and command for “Dismiss” to (`C-q`, `transient-quit-all`) for conform with existing Transient convention.
3.  Reserve the `q` binding for a mode-specific quit command.
4.  Continue Casual convention of displaying “‹Back” and “Dismiss” with support to hide them with a user-defined setting (customizable variable) in a future release.

On point (4), I strongly feel that UI discovery matters and can not presume that users will have a priori knowledge of Transient conventions. Having their visibility be settable I think should address user preference to not see them.

The following table summarizes the changes.

| Label   | Binding | Command            | Notes                                                            |
|------- |------- |------------------ |---------------------------------------------------------------- |
| ‹Back   | `C-g`   | transient-quit-one | This covers scenario 2. Will support hiding in future release.   |
| Dismiss | `C-q`   | transient-quit-all | This covers scenario 1. Will support hiding in future release.   |
| Quit    | q       | mode-specific      | This covers scenario 3 and will only be used for top-level menu. |

I’m at a point where code consolidation among the different Casual packages is desired (aka `casual-lib`). My current thinking is that `casual-lib` is the place to introduce the aforementioned user-defined setting which will create a dependency on this and other packages relying on it.

**Comment by tarsius** [comment]
> On point (4), I strongly feel that UI discovery matters and can not presume that users will have a priori knowledge of Transient conventions. Having their visibility be settable I think should address user preference to not see them.

Sounds reasonable.

> I’m at a point where code consolidation among the different Casual packages is desired (aka `casual-lib`). My current thinking is that `casual-lib` is the place to introduce the aforementioned user-defined setting which will create a dependency on this and other packages relying on it.

Since you have written multiple such packages, it must make sense to factor out some common parts. Writing your own library, as you have decided to do, also has the advantage that you don't have to try to immediately upstream every common abstraction. Some users in the "every dependency is evil" crowd won't be pleased, but as the maintainer of Transient, I appreciate it.

Changes in Transient are often the result of me or someone else trying to do something that isn't explicitly supported yet. When it is me who has discovered a gap, I often solve it in the dependant package first (e.g., by creating a new class). When someone else runs into missing functionality, the pressure is higher to immediately do something about it in Transient itself, which tends to lead to inferior results. Having all the things that you miss from Transient in a single place, will make it easier for me to observe those gaps. It also allows *you* to iterate on potential remedies, before proposing something to me.

**Comment by kickingvegas** [comment]
@tarsius followup: `casual-lib` 1.1.0 now has support for customizable variable `casual-lib-hide-navigation` which will hide the navigation controls (`C-g`, `C-q`) from Casual porcelains. https://github.com/kickingvegas/casual-lib/releases/tag/1.1.0
